version: '3'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks: 
      - backend
    volumes:
      - "./api/:/usr/src/app"
      - "reserved:/usr/src/app/node_modules"
  app:
    build: ./plant-id
    ports:
      - 80:80
    networks: 
      - backend

  database:
    image: "mongo" 
    #ports:
    #  - "27017:27017"
    networks: 
      - backend
    environment:
      - MONGO_INITDB_DATABASE=plantid

volumes:
  reserved:

networks:
  backend: